- name: "Step 1: Run a full batch test on Gemini for code exploits"
  command: "batch-evaluate"
  params:
    category: "Code_Generation_Exploits"
    model: "gemini/gemini-1.5-flash-latest"

- name: "Step 2: Run a single, high-stakes jailbreak test on the same model"
  command: "evaluate"
  params:
    prompt_id: "JBR_001"
    model: "gemini/gemini-1.5-flash-latest"
    mode: "governance"